a = float(input('Digite o valor de A: '))
b = float(input('Digite o valor de B: '))
c = float(input('Digite o valor de C: '))
delta = (b**2 - 4 * a * c)
print("O valor de delta é: ", delta)
if (a > 0) : print("Concavidade voltada para cima (u).")
else: print("Concavidade voltada para baixo (∩).")
if (delta > 0): print("Raízes: ", ( -b + delta**0.5 ) / (2 * a)," e ", ( -b - delta**0.5 ) / (2 * a))
if (delta == 0): print("Raíz: ", (-b + delta**0.5) / (2 * a)) 
if (delta < 0): print("Vértice: ", -( b / (2 * a) ), -( delta / (4 * a )) )
input("Pressione enter para sair...")
